name: 16-environments
run-name: 16 - Working with Environments | env - ${{inputs.target-env}}
on:
 workflow_dispatch:
     inputs:
        target-env:
          type: environment
          default: staging
          



jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{inputs.target-env}}
    env:
        my-env-value: ${{vars.MYENV_VALUE || 'default value'}}
    steps:
        - name: Echo vars
          run: |
            echo "env variables: ${{env.my-env-value}}"