name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS | BB - ${{ inputs.base-branch}} = ${{ inputs.target-branch}}

on: 
 workflow_dispatch:
        inputs:
            base-branch:
                type: string
                default: main
            target-branch:
                type: string
                default: update-dependencies
            working-dir:
                type: string
                default: 17-custon-actions/react-app

jobs:
    dependency-update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: checkout the code
              uses: ./.github/actions/js-dependency-update
            