name: 17 - 3 - Custom Actions - Docker

on:
 workflow_dispatch:
    inputs:
        url: 
            type: string
            default: 'https://www.google.com'

jobs:
    ping-url:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@4
            - name: ping url
              uses: ./.github/actions/docker-ping-url
              
