name: 17 - 3 - Custom Actions - Docker

on:
 workflow_dispatch:
    inputs:
        url: 
            type: choice
            options: 
                - 'https://www.google.com'
                - 'https://wwwf.google.com'
        max_trials:
            required: false
            description: Maximum number of trials until action fails
            default: '10'
        delay:
            required: false
            description: Delay in seconds between trials
            default: '5'

jobs:
    ping-url:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: ping url
              uses: ./.github/actions/docker-ping-url
              with:
                url: ${{inputs.url}}
                max_trials: ${{ inputs.max_trials}}
                delay: ${{ inputs.delay}}
